import { ReceiptData, formatTokens } from "@/lib/receipt";

interface Props {
  data: ReceiptData;
}

export function ReceiptLedger({ data }: Props) {
  const items = data.models && data.models.length > 0
    ? data.models
    : [{
        agent: "claude-code",
        model: data.model,
        in: data.inputTokens,
        out: data.outputTokens,
        cw: data.cacheWriteTokens,
        cr: data.cacheReadTokens,
        cost: data.cost,
      }];

  return (
    <div
      className="w-full overflow-hidden rounded-lg bg-[#f7f1e6] text-[#23201c] shadow-xl"
      style={{ fontFamily: "Georgia, 'Times New Roman', serif" }}
    >
      <div className="border-b border-[#d8c6a8] bg-[#2f473f] px-5 py-5 text-[#f7f1e6] sm:px-6">
        <div className="grid gap-3">
          <div className="grid gap-1 sm:flex sm:items-start sm:justify-between sm:gap-4">
            <div className="text-[10px] uppercase tracking-[0.28em] text-[#d5c39e]">Tickel ledger</div>
            <div className="font-mono text-[11px] text-[#d5c39e]">{data.date}</div>
          </div>
          <div className="break-words text-2xl font-semibold leading-tight">{data.title}</div>
        </div>
      </div>

      <div className="px-5 py-5 sm:px-6">
        <div className="grid grid-cols-2 gap-3 border-b border-[#d8c6a8] pb-4">
          <Metric label="Input" value={formatTokens(data.inputTokens)} />
          <Metric label="Output" value={formatTokens(data.outputTokens)} />
          <Metric label="Cache write" value={formatTokens(data.cacheWriteTokens)} />
          <Metric label="Cache read" value={formatTokens(data.cacheReadTokens)} />
        </div>

        <div className="mt-4 space-y-3">
          {items.map((item, index) => (
            <div key={`${item.agent}-${item.model}-${index}`} className="grid gap-2 text-sm sm:grid-cols-[1fr_auto] sm:gap-3">
              <div className="min-w-0">
                <div className="break-words font-semibold leading-snug">{item.model}</div>
                <div className="mt-0.5 text-[11px] uppercase tracking-[0.16em] text-[#7d6f59]">{item.agent ?? "agent"}</div>
              </div>
              <div className="font-mono text-sm font-bold sm:shrink-0 sm:text-right">${item.cost.toFixed(4)}</div>
            </div>
          ))}
        </div>

        <div className="mt-5 grid gap-2 border-t border-[#d8c6a8] pt-4 sm:grid-cols-[1fr_auto] sm:items-end sm:gap-4">
          <div>
            <div className="text-[10px] uppercase tracking-[0.28em] text-[#7d6f59]">Total</div>
            <div className="text-xs text-[#7d6f59]">Generated by Tickel</div>
          </div>
          <div className="font-mono text-2xl font-black sm:text-right">${data.cost.toFixed(4)}</div>
        </div>
      </div>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-[0.18em] text-[#7d6f59]">{label}</div>
      <div className="mt-1 font-mono text-lg font-bold">{value}</div>
    </div>
  );
}
