import { ReceiptData, formatTokens } from "@/lib/receipt";

interface Props {
  data: ReceiptData;
}

export function ReceiptDefault({ data }: Props) {
  const rows = [
    { label: "INPUT",       value: formatTokens(data.inputTokens) },
    { label: "OUTPUT",      value: formatTokens(data.outputTokens) },
    { label: "CACHE WRITE", value: formatTokens(data.cacheWriteTokens) },
    { label: "CACHE READ",  value: formatTokens(data.cacheReadTokens) },
  ];

  return (
    <div
      id="receipt"
      className="bg-white w-72 font-mono text-xs px-6 py-8 shadow-md"
      style={{ fontFamily: "'Courier New', monospace" }}
    >
      {/* Header */}
      <div className="text-center mb-4">
        <div className="text-lg font-bold tracking-widest">TICKEL</div>
        <div className="text-gray-500 text-[10px] tracking-widest">TOKEN RECEIPT</div>
      </div>

      <div className="border-t border-dashed border-gray-300 my-3" />

      {/* Project info */}
      <div className="mb-3">
        <div className="flex justify-between">
          <span className="text-gray-500">PROJECT</span>
          <span className="font-bold uppercase">{data.title}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">DATE</span>
          <span>{data.date}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-gray-500">MODEL</span>
          <span className="text-[10px]">{data.model}</span>
        </div>
      </div>

      <div className="border-t border-dashed border-gray-300 my-3" />

      {/* Token rows */}
      {rows.map((row) => (
        <div key={row.label} className="flex justify-between py-0.5">
          <span className="text-gray-500">{row.label}</span>
          <span>{row.value}</span>
        </div>
      ))}

      <div className="border-t border-gray-400 my-3" />

      {/* Cost */}
      <div className="flex justify-between text-sm font-bold">
        <span>TOTAL</span>
        <span>${data.cost.toFixed(4)}</span>
      </div>

      <div className="border-t border-dashed border-gray-300 my-3" />

      {/* Footer */}
      <div className="text-center text-[9px] text-gray-400 tracking-widest">
        GENERATED BY TICKEL
      </div>
    </div>
  );
}
