#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const MODELS_DEV_API_URL = "https://models.dev/api.json";
const ROOT = process.cwd();
const OUTPUT_PATH = path.join(ROOT, "packages", "cli", "src", "generated", "prices.ts");
const CHANGELOG_PATH = path.join(ROOT, "docs", "CHANGELOG.md");

const OFFICIAL_PROVIDERS = [
  "openai",
  "anthropic",
  "google",
  "xai",
  "mistral",
  "cohere",
  "deepseek",
  "moonshotai",
  "alibaba",
  "zhipuai",
  "minimax",
];

const args = new Set(process.argv.slice(2));
const updateChangelog = args.has("--changelog");

function fail(message) {
  console.error(`sync-prices: ${message}`);
  process.exit(1);
}

function isNumber(value) {
  return typeof value === "number" && Number.isFinite(value);
}

function extractModels(providerId, provider) {
  if (!provider || typeof provider !== "object") {
    fail(`provider ${providerId} is missing from models.dev response`);
  }

  const models = provider.models;
  if (!models || typeof models !== "object") {
    fail(`provider ${providerId} has no models object`);
  }

  return Object.values(models)
    .filter((model) => {
      const cost = model?.cost;
      return model?.id && cost && isNumber(cost.input) && isNumber(cost.output);
    })
    .map((model) => ({
      provider: providerId,
      model: model.id,
      input: model.cost.input,
      output: model.cost.output,
      cache_write: isNumber(model.cost.cache_write) ? model.cost.cache_write : 0,
      cache_read: isNumber(model.cost.cache_read) ? model.cost.cache_read : 0,
    }))
    .sort((a, b) => a.model.localeCompare(b.model));
}

function buildGeneratedSource(records) {
  const providerList = OFFICIAL_PROVIDERS.map((provider) => `  "${provider}",`).join("\n");
  const priceEntries = records.map((record) => {
    const key = `${record.provider}/${record.model}`;
    return [
      `  "${key}": {`,
      `    provider: "${record.provider}",`,
      `    model: "${record.model}",`,
      `    input: ${record.input},`,
      `    output: ${record.output},`,
      `    cache_write: ${record.cache_write},`,
      `    cache_read: ${record.cache_read},`,
      "  },",
    ].join("\n");
  }).join("\n");

  const index = new Map();
  for (const record of records) {
    const key = `${record.provider}/${record.model}`;
    const keys = index.get(record.model) ?? [];
    keys.push(key);
    index.set(record.model, keys);
  }

  const indexEntries = [...index.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([model, keys]) => `  "${model}": [${keys.map((key) => `"${key}"`).join(", ")}],`)
    .join("\n");

  return `// Generated by scripts/sync-prices.mjs from ${MODELS_DEV_API_URL}.
// Do not edit by hand.

export interface GeneratedModelPricing {
  provider: string;
  model: string;
  input: number;
  output: number;
  cache_write: number;
  cache_read: number;
}

export const PRICE_SOURCE_URL = "${MODELS_DEV_API_URL}";

export const OFFICIAL_PROVIDER_ALLOWLIST = [
${providerList}
] as const;

export const GENERATED_MODEL_PRICES: Record<string, GeneratedModelPricing> = {
${priceEntries}
};

export const MODEL_ID_INDEX: Record<string, string[]> = {
${indexEntries}
};
`;
}

function updateChangelogEntry() {
  const entry = "- **chore**: 同步官方模型价格表";
  const changelog = fs.readFileSync(CHANGELOG_PATH, "utf8");
  const match = changelog.match(/^## Unreleased\n([\s\S]*?)(?=^## |\Z)/m);
  if (!match) fail("docs/CHANGELOG.md is missing ## Unreleased");

  const body = match[1];
  if (body.includes(entry)) return;

  const replacement = body.trim()
    ? `## Unreleased\n\n${entry}\n${body}`
    : `## Unreleased\n\n${entry}\n\n`;

  fs.writeFileSync(
    CHANGELOG_PATH,
    changelog.replace(/^## Unreleased\n[\s\S]*?(?=^## |\Z)/m, replacement),
  );
}

const response = await fetch(MODELS_DEV_API_URL);
if (!response.ok) {
  fail(`failed to fetch ${MODELS_DEV_API_URL}: ${response.status} ${response.statusText}`);
}

const data = await response.json();
const records = OFFICIAL_PROVIDERS.flatMap((providerId) => extractModels(providerId, data[providerId]));
const nextSource = buildGeneratedSource(records);
const currentSource = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : null;
const changed = currentSource !== nextSource;

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, nextSource);

if (updateChangelog && changed) {
  updateChangelogEntry();
}

console.log(`Synced ${records.length} model prices from ${OFFICIAL_PROVIDERS.length} providers.`);
console.log(`Wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
if (updateChangelog && changed) {
  console.log(`Updated ${path.relative(ROOT, CHANGELOG_PATH)}`);
}
if (!changed) {
  console.log("Price table is already up to date.");
}
